timezone: Asia/Calcutta
permalink: :title

markdown: kramdown

author:
  name: Sachin Sachin
  email: sachin@jsrockstar.com

# Custom URL Git Repo URL
baseurl: ''
url: ''

# Default Git Repo URL
# baseurl: http://sachinsaluja.com
# url: http://sachinsaluja.github.io

# Localhost Repo URL
# baseurl: ''
# url: http://host.sachinsaluja.com:4000

# Localhost Repo URL
# baseurl: ''
# url: http://localhost:4000